In [1]:
import sys
sys.path.append("../src")

In [2]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
%matplotlib notebook

# Load dataset and do some preprocessing

In [3]:
train_path = "../data/train.csv"

In [4]:
df_data = pd.read_csv(train_path, sep=",")

In [5]:
df_data.head()

full_label    TSPAN6      TNMD      DPM1     SCYL3  C1orf112       CFH  \
0  369_M01_CTRL  8.869526  5.648693  7.664066  8.370360  6.257695  5.270360   
1  369_M05_CTRL  8.705657  5.932060  7.820206  8.362421  6.140431  5.573240   
2  371_M02_CTRL  8.623002  3.984119  7.419094  8.498542  6.160291  5.588960   
3  371_M07_CTRL  9.434875  5.866242  8.337313  8.139628  7.505509  3.984119   
4  371_M11_CTRL  9.055039  5.240241  7.811833  8.236604  6.829787  4.793247   

      FUCA2      GCLC      NFYA  ...  AC069544.2  AC006460.2  AL356275.1  \
0  7.475895  8.269031  8.279492  ...    5.319481    5.045370    5.648693   
1  7.791254  8.201606  8.122618  ...    4.741939    4.523022    5.534549   
2  8.013386  7.919199  8.520048  ...    5.588960    5.146627    4.816944   
3  7.329864  8.352620  8.048476  ...    3.984119    3.984119    4.650987   
4  7.691507  8.441777  8.376590  ...    4.968903    4.559957    5.453445   

   AC092329.4    MIR205  AC066615.1  AC105233.5  AC073111.5  AC079781.5  label  
0    6.235458  4.523640    3.984119    4.523640    5.218771    5.319481      0  
1    6.014217  4.523022    3.984119    5.105518    5.268960    5.409834      0  
2    6.716586  4.816944    3.984119    4.816944    5.146627    5.390389      0  
3    5.553634  4.650987    3.984119    4.919178    3.984119    4.650987      0  
4    6.161526  4.559957    3.984119    4.559957    5.240241    5.787031      0  

[5 rows x 15106 columns]

In [6]:
df_features = df_data[df_data.columns.difference(['full_label', 'label'])]
df_labels = df_data["label"]

In [7]:
df_features.head()

A1BG-AS1        A2M     A2ML1    A4GALT      AAAS      AACS     AADAT  \
0  4.908175  12.037180  5.045370  5.045370  7.381365  8.263771  5.164377   
1  4.523022  12.272072  5.105518  5.217421  7.398009  8.515874  5.749570   
2  5.758390   6.039895  5.146627  3.984119  7.982674  8.432022  6.991751   
3  3.984119  11.059675  3.984119  3.984119  6.807586  7.532781  7.390862   
4  4.968903  10.311189  4.559957  3.984119  7.458173  8.095056  6.796347   

      AAED1     AAGAB      AAK1  ...    ZYG11B       ZYX     ZZEF1      ZZZ3  \
0  6.423369  8.350658  8.210091  ...  8.616981  6.765996  8.704889  8.976108   
1  6.255497  8.001646  7.956770  ...  8.630280  6.669450  8.827865  9.128019   
2  5.758390  8.719075  8.237920  ...  7.982674  6.466886  8.826486  9.121773   
3  6.258603  8.993143  8.290386  ...  8.827956  3.984119  8.678210  9.346056   
4  6.161526  8.319912  8.224298  ...  8.720871  5.453445  8.473294  9.621207   

    août-01   août-02   août-03   août-04  janv.-01  snoU2_19  
0  8.608716  9.066324  8.570926  8.886709  7.581604  4.366722  
1  8.795552  9.201074  8.580553  8.855992  7.463924  3.984119  
2  8.541237  9.107652  8.476709  8.602993  8.157784  3.984119  
3  8.367766  9.031639  9.114668  8.849671  8.139628  3.984119  
4  8.493928  9.181128  8.901494  8.983960  8.308303  3.984119  

[5 rows x 15104 columns]

In [8]:
df_labels.head()

0    0
1    0
2    0
3    0
4    0
Name: label, dtype: int64

## Set X (y) matrix(vector)

In [9]:
X = df_features.values
print(X.shape)

(29, 15104)


In [10]:
y = df_labels.values
print(y.shape)

(29,)


# Logistic regression

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [12]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(21, 15104)
(21,)
(8, 15104)
(8,)


## Define the models

In [13]:
clf_l1_LR = LogisticRegression(penalty='l1', solver='saga', max_iter=1000, multi_class='multinomial')
clf_l2_LR = LogisticRegression(penalty='l2', solver='saga', max_iter=1000, multi_class='multinomial')

## Train models

In [14]:
clf_l1_LR.fit(x_train, y_train)

/Users/sinitame/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [15]:
clf_l2_LR.fit(x_train, y_train)

/Users/sinitame/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='multinomial', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

## Test models

In [16]:
predictions_l1 = clf_l1_LR.predict(x_test)

In [17]:
predictions_l2 = clf_l2_LR.predict(x_test)

In [18]:
score_l1 = clf_l1_LR.score(x_test, y_test)
print(score_l1)

0.5


In [19]:
score_l2 = clf_l2_LR.score(x_test, y_test)
print(score_l1)

0.5


In [20]:
cm_l1 = metrics.confusion_matrix(y_test, predictions_l1)
print(cm_l1)

[[0 1 0]
 [0 2 0]
 [3 0 2]]


In [21]:
cm_l2 = metrics.confusion_matrix(y_test, predictions_l2)
print(cm_l2)

[[0 1 0]
 [0 2 0]
 [3 0 2]]


## Informations about the models

In [22]:
coef_l1_LR = clf_l1_LR.coef_.ravel()
coef_l2_LR = clf_l2_LR.coef_.ravel()

# coef_l1_LR contains zeros due to the
# L1 sparsity inducing norm

sparsity_l1_LR = np.mean(coef_l1_LR == 0) * 100
sparsity_l2_LR = np.mean(coef_l2_LR == 0) * 100

In [23]:
print("Number of parameters", len(coef_l1_LR))
print("Sparcity", sparsity_l1_LR)

Number of parameters 45312
Sparcity 92.53840042372882


In [24]:
print(sparsity_l2_LR)

0.0


## Relevant features

In [25]:
print(clf_l1_LR.coef_.shape)

(3, 15104)


In [26]:
categories = {}

for i,cat_features in enumerate(clf_l1_LR.coef_):
    relevant_features = np.where(cat_features != 0)
    categories[i] = df_features.columns[relevant_features].to_list()
    print("Number of relevant features for category {} :".format(i),len(relevant_features[0]))
    

Number of relevant features for category 0 : 1193
Number of relevant features for category 1 : 1198
Number of relevant features for category 2 : 990


In [27]:
def intersection(lst1, lst2): 
    return list(set(lst1) & set(lst2))

In [28]:
intersection_cat0_cat1 = intersection(categories[0], categories[1])
print("Common features between cat0 and cat1", len(intersection_cat0_cat1))

Common features between cat0 and cat1 532


In [29]:
intersection_cat1_cat2 = intersection(categories[1], categories[2])
print("Common features between cat1 and cat2", len(intersection_cat1_cat2))

Common features between cat1 and cat2 338


In [30]:
intersection_cat2_cat0 = intersection(categories[2], categories[0])
print("Common features between cat2 and cat0", len(intersection_cat2_cat0))

Common features between cat2 and cat0 342


In [31]:
from collections import Counter
from collections import defaultdict

def get_uncommon_features(categories):
    n = len(categories.keys())
    intersection  = []
    unique_features = {}
    
    for k in range(n):
        unique_features[k] = Counter(categories[k])
    
    for i in range(n):
        features_cat0 = Counter(categories[i%3])
        features_cat1 = Counter(categories[(i+1)%3])
        intersection = features_cat0 & features_cat1
        unique_features[i] = unique_features[i] - intersection
        unique_features[(i+1)%3] = unique_features[(i+1)%3] - intersection
    
    for k in range(n):
        unique_features[k] = list(unique_features[k].elements())
    
    return unique_features

In [32]:
unique_features = get_uncommon_features(categories)

In [33]:
print("Unique features for category 0:", len(unique_features[0]))

Unique features for category 0: 418


In [34]:
print("Unique features for category 1:", len(unique_features[1]))

Unique features for category 1: 427


In [35]:
print("Unique features for category 2:", (len(unique_features[2])))

Unique features for category 2: 409
